# Load packages ----------------------------------------
library(tidyverse)
library(RGCCA)
library(r.jive)
library(IntNMF)
library(omicade4)
library(GPArotation)
library(MOFA2)
library(tensorBSS)
library(LUCIDus)
library(networkD3)
library(HIMA)
library(factoextra)
library(diagram)
library(plotly)
library(reshape2)
library(cowplot)
library(psych)
ggplot2::theme_set(cowplot::theme_cowplot())

# devtools::install_github("cran/RMediation")
library(RMediation)
library(mclust)
library(data.table)
library(colorspace)
library(tidytext)

library(boot)
library(xtune)
library(htmlwidgets)
library(parallel)
library(oaqc)
library(concaveman)
