project:
  type: book

book:
  title: "Multi-omic Analyses for Precision Health"
  author: "Jesse Goodrich, Hongxu Wang, Qiran Jia, and David Conti"
  date: "8/7/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - HIMA.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    embed-resources: true
    self-contained-math: true
    self-contained: true
    theme: cosmo

editor: visual

