project:
  type: book

book:
  title: "Precision Health with Multi-Omics and Environmental Data: A Prime"
  author: "Goodrich JA, Wang H, Jia Q, and Conti D."
  date: "8/20/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - HIMA.qmd
    - Mediation_with_latent_fctrs.qmd
    - Quasi_mediation.qmd
    - software.qmd
    - appendix_code.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    code-fold: true
    theme: cosmo
    self-contained: true
    self-contained-math: true
  pdf: 
    toc: true
    number-sections: true
    colorlinks: true
    geometry:
      - top=20mm
      - left=20mm
      - right=20mm
      - heightrounded
  
  
editor: source