project:
  type: book

book:
  title: "Multi-omic Analyses for Precision Health"
  author: "Jesse Goodrich, Hongxu Wang, Qiran Jia, and David Conti"
  date: "8/10/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - HIMA.qmd
    - Lucid Early Integration.qmd
    - Lucid in Parallel.qmd
    - Lucid in Serial.qmd
    - appendix_code.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    code-fold: true
    theme: cosmo
    self-contained: true
    self-contained-math: true
  
editor: visual

