# Preface {.unnumbered}

The integration of multiple omics datasets offers unprecedented insights into the complex interplay of environmental and biological factors, providing a comprehensive picture of individual health and disease. However, to harness the full potential of multiomics data, researchers need a robust framework for understanding how and why to perform different multiomic integration techniques as well as .

This book is intended as a resource for researchers aiming to incorporate omics datasets to understand how environmental or genetic factors impact human health and disease. Our goal is to explain the concepts, techniques, and methodologies that can allow resaerchers to fully leverage the information contained in multidimensional datasets in order to obtain biologicially relevent and actionable insights into environmental and genetic impacts on diesease.

This book is also indended to companion the manuscript by Goodrich et al. (2023, in developmen), which presents an overarching framework for the integration of various omics data sets in a mediation-type framework. The present book builds upon this manuscript by providing step by step instructions along with a reproducible example of how to perform the analysis outlined in the manuscript. 